### ISSUE TITLE
canceling or pausing

### ISSUE THREAD

**Issue by abdelaziz-mahdy** [qiaoshouqing/dio_range_download#2]
how can i cancel or pause the download 

and if there is a way to delete the canceled download chunks.

**Comment by qiaoshouqing** [comment]
Not supported for the time being

**Comment by abdelaziz-mahdy** [comment]
oh will wait for them♥

**Comment by narumi147** [comment]
`Dio` supports canceling the download task by passing a `CancelToken`, please add a `cancelToken` parameter in `RangeDownload.downloadWithChunks` and pass it to every child task.

**Comment by abdelaziz-mahdy** [comment]
And in case of errors deleteonerror should be false

**Comment by qiaoshouqing** [comment]
> And in case of errors deleteonerror should be false

deleteonerror is Dio‘s parameter.But dio_range_download never delete on error.So this paramater may be useless.

**Comment by qiaoshouqing** [comment]
> `Dio` supports canceling the download task by passing a `CancelToken`, please add a `cancelToken` parameter in `RangeDownload.downloadWithChunks` and pass it to every child task.

Done

**Comment by abdelaziz-mahdy** [comment]
> > And in case of errors deleteonerror should be false
> 
> deleteonerror is Dio‘s parameter.But dio_range_download never delete on error.So this paramater may be useless.

Dio cancel token is considered an error 

And incase of network problems the download will get deleted if deleteonerror is not set to false

**Comment by narumi147** [comment]
Agree with @zezo357 , and I would like to add  something more about this.

As `range_downlod` won't delete any temp file and `Dio` delete file on failed. So if you do nothing, and one chunk download failed, the temp files of other chunks will still remain on disk. It should be against design principle, otherwise you provide file transfer resume.

- If won't provide (fake) file transfer resume:
pass `deleteOnError` to every `Dio` chunk task, then if any error raised:
  - If `deleteOnError=true` and the error is cancel by user: all tasks canceled  and need to delete all temp files even if it is download successfully. So here you also need to create a `CancelToken` if user not provided. 
  - In other situations, remain the default behaviour.

- If new feature of support file transfer resume(fake) added:
If enabled, `deleteOnError` should always be `false`. I use `fake` here is because a simple solution is to resume failed chunks only. Once resume, check the validity(like checksum or something else) of previous downloaded temp chunks.

**Comment by qiaoshouqing** [comment]
@zezo357 @narumishi You are right.I will fix it.
